FROM --platform=$BUILDPLATFORM golang:1.25.0-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
ARG APP_COMMAND=lambda
ARG TARGETOS=linux
ARG TARGETARCH=arm64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -trimpath -ldflags="-s -w" -o /out/bootstrap ./cmd/${APP_COMMAND}

FROM public.ecr.aws/lambda/provided:al2023

COPY --from=build /out/bootstrap /var/runtime/bootstrap

CMD ["bootstrap"]
